registroCore/Models/ErrorViewModel.cs
using System;

namespace registroCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

registroCore/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace registroCore.Models
{
    public class Persona
    {
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string nombre { get; set; }


        [Required(ErrorMessage = "El email es obligatorio")]
        [DataType(DataType.EmailAddress)]

        public string correo { get; set; }


        [Required(ErrorMessage = "La fecha es obligatoria")]
        [DataType(DataType.Date)]
        public DateTime fechaNacimiento { get; set; }
        
        

    }
}

registroCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using registroCore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace registroCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

registroCore/Controllers/PersonasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using registroCore.Data;
using registroCore.Models;
//using System.Threading.Tasks;

namespace registroCore.Controllers
{
    public class PersonasController : Controller
    {

        private readonly personaDbContext _context;

        public PersonasController(personaDbContext context)
        {
            _context = context;
        }
        //Http Get Index
        public IActionResult Index()
        {
            IEnumerable<Persona> ListaPersonas = _context.Persona;
            return View(ListaPersonas);
        }
        //Http Get Create
        public IActionResult Create()
        {
           return View();
        }
        //Http Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        // ValidateAntiForgeryToken se usa para protejer los formularios

        public IActionResult Create(Persona persona)
        {
            if(ModelState.IsValid)
            {
                _context.Persona.Add(persona);
                _context.SaveChanges();
                TempData["mensaje"] = "Persona registrada con exito";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Http Get Edit
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            //Obtener persona
            var persona = _context.Persona.Find(id);
            if (persona == null)
            {
                return NotFound();

            }
            return View(persona);
        }
        //Http Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Edit(Persona persona)
        {
            if (ModelState.IsValid)
            {
                _context.Persona.Update(persona);
                _context.SaveChanges();
                TempData["mensaje"] = "Actualizacion exitosa";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Http Get delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //Obtener persona
            var persona = _context.Persona.Find(id);
            if (persona == null)
            {
                return NotFound();

            }
            return View(persona);
        }
        //Http Get Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePersona(int? id)
        {
            //Obterner persona por id
            var persona = _context.Persona.Find(id);
            
            if (persona == null)
            {
                return NotFound();
               
            }
            _context.Persona.Remove(persona);
            _context.SaveChanges();
            TempData["mensaje"] = "Registro borrado con exito";
            return RedirectToAction("Index");
        }
    }
    }

registroCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

registroCore/Views/Personas/Create.cshtml
@model registroCore.Models.Persona
@{
    ViewData["Title"] = "Registrar nueva persona";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Registrar nueva persona</h3>
        </div>
        <div class="row">
            <div class="col-sm-10">
                <form method="post" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="nombre" class="control-label"></label>
                        <input asp-for="nombre" class="form-label">
                        <span asp-validation-for="nombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="correo" class="control-label"></label>
                        <input asp-for="correo" class="form-label">
                        <span asp-validation-for="correo" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <label asp-for="fechaNacimiento" class="control-label"></label>
                        <input asp-for="fechaNacimiento" class="form-label">
                        <span asp-validation-for="fechaNacimiento" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <input type="submit" value="Registrar persona" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
@{<partial name="_ValidationScriptsPartial"/>}
}

registroCore/Views/Personas/Delete.cshtml
@model registroCore.Models.Persona

@{
    ViewData["Title"] = "Eliminar persona";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar persona</h3>
        </div>
        <div class="row">
            <div class="col-sm-10">
                <form method="post" asp-action="DeletePersona">
                    <input type="hidden" asp-for="id" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="nombre" class="control-label"></label>
                        <input asp-for="nombre" class="form-label" disabled>
                        <span asp-validation-for="nombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="correo" class="control-label"></label>
                        <input asp-for="correo" class="form-label" disabled>
                        <span asp-validation-for="correo" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <label asp-for="fechaNacimiento" class="control-label"></label>
                        <input asp-for="fechaNacimiento" class="form-label" disabled>
                        <span asp-validation-for="fechaNacimiento" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <input type="submit" value="Eliminar persona" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

registroCore/Views/Personas/Edit.cshtml
@model registroCore.Models.Persona

@{
    ViewData["Title"] = "Editar persona";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Editar persona</h3>
        </div>
        <div class="row">
            <div class="col-sm-10">
                <form method="post" asp-action="Edit">
                    <input type="hidden" asp-for="id" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="nombre" class="control-label"></label>
                        <input asp-for="nombre" class="form-label">
                        <span asp-validation-for="nombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="correo" class="control-label"></label>
                        <input asp-for="correo" class="form-label">
                        <span asp-validation-for="correo" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <label asp-for="fechaNacimiento" class="control-label"></label>
                        <input asp-for="fechaNacimiento" class="form-label">
                        <span asp-validation-for="fechaNacimiento" class="text-danger"></span>

                    </div>
                    <div class="form-group">
                        <input type="submit" value="Actualizar persona" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

registroCore/Views/Personas/Index.cshtml
@model IEnumerable<registroCore.Models.Persona>

@{
    ViewData["Title"] = "Lista de personas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @if(TempData["mensaje"] != null)
            {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @TempData["mensaje"]
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
            }
    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de personas</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Personas">Registrar nuevo</a>
        </div>
    </div>
    <div class="row">
        @if(Model.Count() > 0)
            {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.id)</td>
                        <td>@Html.DisplayNameFor(m => m.nombre)</td>
                        <td>@Html.DisplayNameFor(m => m.correo)</td>
                        <td>@Html.DisplayNameFor(m => m.fechaNacimiento)</td>
                        <td>Aciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.nombre</td>
                        <td>@item.correo</td>
                        <td>@item.fechaNacimiento</td>
                        <td>
                            <a asp-controller="Personas" asp-action="Edit" asp-route-id="@item.id" class="btn btn-warning">Editar</a>
                            <a asp-controller="Personas" asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger">Eliminar</a>
                        </td>
                     </tr>
                        }

</tbody>
            </table>
            }
            else
            {
                <p>No existen registros</p>
            }
    </div>
</div>

registroCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - registroCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">registroCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index"> CRUD Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - registroCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>